name: cancer-de-pancreas
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - scikit-learn
    - plotly
    - streamlit
    - openpyxl
    - watchdog